### ISSUE TITLE
[crash] java.lang.Throwable: Unable to fetch installed components

### ISSUE THREAD

**Issue by Daschi1** [WarningImHack3r/intellij-shadcn-plugin#21]
### What is the issue?

I installed the plugin having a fresh shadcn sveltekit project open. I then opened the sidepanel and it threw the error message.

### What are the steps to reproduce this issue?

1. Initialize a fresh shadcn sveltekit project, as described here: https://www.shadcn-svelte.com/docs/installation/sveltekit. Complete up to step 6 (don't add a component yet) (using typescript and pnpm).
2. Open the project in WebStorm
3. Install the plugin
4. Open the sidepanel

### What were you expecting to happen?

I did not expect an error message to be thrown.

### Paste any relevant logs, error output, etc.

```shell
java.lang.Throwable: Unable to fetch installed components
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.github.warningimhack3r.intellijshadcnplugin.backend.sources.Source.getInstalledComponents(Source.kt:100)
	at com.github.warningimhack3r.intellijshadcnplugin.ui.ISPWindowContents$panel$1$1$invokeSuspend$$inlined$runReadAction$2.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.github.warningimhack3r.intellijshadcnplugin.ui.ISPWindowContents$panel$1$1.invokeSuspend(ISPWindowContents.kt:244)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineSchedul

<TRIMMED STACKTRACE>
```

### What OS are you experiencing the problem on?

Windows

### Additional platform information

Build version: WebStorm 2023.3.5 Build: #WS-233.14808.24 March 13, 2024
JRE: 17.0.10+1-b1087.21, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.21, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Atom Material Icons (94.1.0), .ignore (4.5.2), .env files support (2024.1), Batch Scripts Support (1.0.13), shadcn/ui Components Manager (0.7.3), GitToolBox (500.2.1+233), WakaTime (14.3.11), Svelte (233.14015.23), One Dark Theme (5.10.0), Rainbow Brackets (2024.2.1), Hunspell (233.14808.24), Discord Integration (1.12.0)]
Disabled plugins:[EditorConfig (233.14808.24)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi, thanks for the report! I see where the issue is, gonna fix that right now

**Comment by WarningImHack3r** [comment]
Update submitted, thanks for the report!
