### ISSUE TITLE
[crash] Unhandled exception in [StandaloneCoroutine{Cancelling}@517f1fe, Dispatchers.Default]

### ISSUE THREAD

**Issue by Daschi1** [WarningImHack3r/intellij-shadcn-plugin#26]
### What is the issue?

I opened the plugin side panel twice in a non shadcn sveltekit project twice, the second time the error got thrown.

### What are the steps to reproduce this issue?

- get a sveltekit project with no shadcn configured
- open the side panel
- it says "no shadcn configuration found"
- close it
- open it again
- the error is thrown, no "no shadcn configuration found" displayed
- closing and reopening after results in no errors, but also no "no shadcn configuration found" message in the pane

### What were you expecting to happen?

I am expecting the plugin not to throw an error and just display the "no shadcn configuration found" message consistently.

### Paste any relevant logs, error output, etc.

```shell
java.lang.IllegalStateException: No shadcn/ui source found
	at com.github.warningimhack3r.intellijshadcnplugin.ui.ISPWindowContents$panel$1$1.invokeSuspend(ISPWindowContents.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@517f1fe, Dispatchers.Default]
```

### What OS are you experiencing the problem on?

Windows

### Additional platform information

Build version: WebStorm 2023.3.5 Build: #WS-233.14808.24 March 13, 2024
JRE: 17.0.10+1-b1087.21, JetBrains s.r.o.
JVM: 17.0.10+1-b1087.21, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [shadcn/ui Components Manager (0.7.5), GitToolBox (500.2.2+233), WakaTime (14.3.11), Svelte (233.14015.23), One Dark Theme (5.10.0), Rainbow Brackets (2024.2.1), Hunspell (233.14808.24), Discord Integration (1.12.0), Atom Material Icons (94.1.0), .ignore (4.5.2), .env files support (2024.1), Batch Scripts Support (1.0.13)]
Disabled plugins:[EditorConfig (233.14808.24)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Thanks for the report! I'm sorry for the inconvenience, but thank you for helping make the plugin stable for 1.0!

**Comment by Daschi1** [comment]
No problem, keep up the good work!
